import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Check, Info, ChevronDown } from 'lucide-react';
import { alphabeticalParties, categories, questions, categoryName } from '../data';
import { useAppState } from '../hooks/useAppState';
import { answerLabels, comparePositions } from '../utils/comparison';
import { EmptyState, MatchBadge, PageHeading, PartyMark } from '../components/ui';
import DocumentedPosition from '../components/DocumentedPosition';
export default function Compare() {
 const [params,setParams]=useSearchParams();const {progress}=useAppState();const [theme,setTheme]=useState('all');const [notice,setNotice]=useState('');
 const initial=params.get('parties');const selected=alphabeticalParties.filter(p=>(initial===null?['pp','psoe']:initial.split(',')).includes(p.id)).slice(0,4);
 function toggle(id:string){if(!selected.some(p=>p.id===id)&&selected.length===4){setNotice('Puedes comparar hasta cuatro formaciones. Quita una para añadir otra.');return;}setNotice('');const next=selected.some(p=>p.id===id)?selected.filter(p=>p.id!==id).map(p=>p.id):[...selected.map(p=>p.id),id];setParams(previous=>{const updated=new URLSearchParams(previous);updated.set('parties',next.join(','));return updated;},{replace:true});}
 const displayed=questions.filter(q=>(theme==='all'||q.categories.includes(theme))&&(!params.get('issue')||params.get('issue')===q.issueId));
 return <div className="container page"><PageHeading eyebrow="PON LAS IDEAS EN PERSPECTIVA" title="Distintas propuestas. Tu criterio." description="Compara hasta cuatro formaciones cuestión por cuestión. Cada compromiso conserva su fecha y fuente; los programas de 2023 no acreditan una posición para 2026." />
 <section className="party-selection"><h2>¿Qué formaciones quieres comparar?</h2><p>Orden alfabético. Seleccionadas: {selected.length} de 4.</p><div className="party-checkboxes">{alphabeticalParties.map(p=><label key={p.id} className={`party-checkbox ${selected.some(x=>x.id===p.id)?'checked':''}`}><input type="checkbox" checked={selected.some(x=>x.id===p.id)} onChange={()=>toggle(p.id)}/><PartyMark party={p} small/><span>{p.name}</span><span className="checkbox-mark" aria-hidden="true">{selected.some(x=>x.id===p.id)&&<Check size={13}/>}</span></label>)}</div>{notice&&<p role="status">{notice}</p>}</section>
 <div className="inline-callout"><Info size={21} aria-hidden="true"/><p>Neutral / No estoy seguro, preguntas saltadas y posiciones desconocidas no producen coincidencias. No hay resumen de afinidad ni ranking.</p><Link className="text-link" to="/metodologia">Cómo se compara</Link></div>
 {!selected.length?<EmptyState title="Elige una perspectiva para empezar" text="Selecciona una o varias formaciones para consultar la documentación." to="/partidos" action="Explorar documentos"/>:<>
 <div className="section-intro"><h2>Las cuestiones, una a una.</h2><label className="select-label">Filtrar por tema<select value={theme} onChange={e=>setTheme(e.target.value)}><option value="all">Todos los temas</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
 <div className="table-scroll" tabIndex={0} role="region" aria-label="Comparación por cuestión, desplaza para ver más formaciones"><table className="comparison-table"><caption>Indicadores por cuestión. Las diferencias de intensidad de tu respuesta no se convierten en una intensidad política del partido.</caption><thead><tr><th scope="col">Cuestión</th><th scope="col">Mi respuesta</th>{selected.map(p=><th scope="col" key={p.id}>{p.acronym}</th>)}</tr></thead><tbody>{displayed.map(q=><tr key={q.id}><th scope="row"><Link to={{pathname:"/comparar",search:`?${params.toString()}`,hash:`#issue-${q.issueId}`}}>{q.statement}</Link><small className="table-coverage">{categoryName(q.category)}</small></th><td>{progress.answers[q.id]===null?'Saltada':progress.answers[q.id]===undefined?'Sin responder':answerLabels[progress.answers[q.id]!]}</td>{selected.map(p=><td key={p.id}><MatchBadge match={comparePositions(progress.answers[q.id],q.positions[p.id]?.position,q.positions[p.id]?.stance)}/><small className="table-coverage">{q.positions[p.id]?.position!=null?q.positions[p.id].summary:'Sin posición suficientemente clara'}</small></td>)}</tr>)}</tbody></table></div>
 <section className="concrete-proposals"><h2>Documentación y matices</h2><div className="proposal-list">{displayed.map(q=><details className="proposal-details" id={`issue-${q.issueId}`} key={q.id}><summary><div><span className="eyebrow">{q.categories.map(categoryName).join(' · ')}</span><h3>{q.statement}</h3><span className="your-response">Asunto: {q.issueId} · {q.relatedProposals.length} registros</span></div><ChevronDown size={20} aria-hidden="true"/></summary><p>{q.context.meaning}</p><p className="muted">{q.importantNuances.join(' ')}</p><div className="proposal-positions">{selected.map(p=><DocumentedPosition key={p.id} question={q} party={p} answer={progress.answers[q.id]}/>)}</div></details>)}</div></section></>}
 </div>;
}
