import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, EyeOff, ShieldCheck, BookOpen, Check, Compass, ScanLine, Sparkles, LockKeyhole } from 'lucide-react';
import { PrivacyNote, OrbitMark } from '../components/ui';
import { categories, questions } from '../data';
import { CategoryIcon } from '../components/Icon';
import { useAppState } from '../hooks/useAppState';
import config from '../config.json';
const steps = [
  { icon: EyeOff, title: 'Responde', description: 'Propuestas concretas, sin siglas ni candidatos. Solo lo que tú piensas.' },
  { icon: Compass, title: 'Ve tus coincidencias', description: 'Descubre tus porcentajes de coincidencia con los partidos y cuántas preguntas se han podido comparar.' },
  { icon: BookOpen, title: 'Consulta las fuentes', description: 'Descubre de dónde viene cada propuesta y lee el documento original.' },
  { icon: ScanLine, title: 'Decide por ti mismo', description: 'La información es nuestra parte. La decisión siempre es tuya.' },
];
export default function Home() {
  const { progress } = useAppState();
  return <div className="home"><section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="tiny-line" /> MENOS ETIQUETAS. MÁS IDEAS.</div><h1>Descubre qué ideas<br className="desktop-break" /> <span>encajan contigo.</span></h1><p className="hero-description">Responde sobre propuestas concretas sin saber inicialmente qué partido las defiende.</p><div className="hero-buttons"><Link className="button primary large" to={progress.completed ? '/resultados' : '/test'}>{progress.completed ? 'Ver mis resultados' : Object.keys(progress.answers).length ? 'Continuar cuestionario' : 'Empezar cuestionario'}<ArrowRight size={19} aria-hidden="true" /></Link><Link className="button secondary large" to="/partidos">Explorar partidos<ArrowUpRight size={18} aria-hidden="true" /></Link></div><div className="hero-details"><span><Check size={15} aria-hidden="true" />{questions.length} preguntas</span><span><Check size={15} aria-hidden="true" />A tu ritmo</span><span><Check size={15} aria-hidden="true" />Sin registro</span></div><PrivacyNote compact /></div>
    <div className="hero-art" aria-label="Ejemplo ilustrativo del cuestionario y del mapa de ideas"><div className="orbit-background"><div className="orbital-ring one" /><div className="orbital-ring two" /><div className="orbital-ring three" /><span className="orbit-dot d1"/><span className="orbit-dot d2"/></div><div className="floating-note"><span className="note-icon"><EyeOff size={17} aria-hidden="true" /></span> Tus ideas primero. Las siglas después.</div><div className="preview-question"><div className="preview-top"><span><span className="live-dot" /> MODO CIEGO</span><span>Ejemplo · 01 / {questions.length}</span></div><div className="preview-progress"><span /></div><div className="preview-category"><BriefcaseIcon />Empleo</div><h2>Reducir progresivamente la jornada laboral máxima manteniendo el salario.</h2><div className="preview-options"><div className="preview-option chosen"><span className="radio-dot" /><span>De acuerdo</span><Check size={16} aria-hidden="true" /></div><div className="preview-option"><span className="radio-dot" /><span>Neutral / No estoy seguro</span></div><div className="preview-option"><span className="radio-dot" /><span>En desacuerdo</span></div></div><div className="preview-bottom"><span><LockKeyhole size={13} aria-hidden="true" /> Solo en tu dispositivo</span><ArrowRight size={16} aria-hidden="true" /></div></div><div className="preview-map"><div className="mini-orbit"><OrbitMark /></div><div><strong>Un mapa. Muchas perspectivas.</strong><p>Sin decirte a quién votar.</p></div><span className="mini-spark"><Sparkles size={18} aria-hidden="true" /></span></div><div className="art-caption">Una conversación con tus propias ideas.</div></div>
    </section><section className="trust-strip container" aria-label="Principios"><div><EyeOff size={19} aria-hidden="true" /><strong>Sin sesgos de marca</strong><span>Primero la propuesta</span></div><div><ShieldCheck size={19} aria-hidden="true" /><strong>Privacidad por diseño</strong><span>Tu navegador, tus respuestas</span></div><div><BookOpen size={19} aria-hidden="true" /><strong>Información transparente</strong><span>Fuentes a un clic</span></div></section>
    <section className="how-section container"><div className="section-intro"><div><p className="eyebrow">ASÍ FUNCIONA</p><h2>Tu criterio, en cuatro pasos.</h2></div><p>No necesitas tener todas las respuestas.<br />Solo un poco de curiosidad.</p></div><div className="steps-grid">{steps.map((step, index) => <article className="step-card" key={step.title}><div className="step-top"><span className="step-icon"><step.icon size={23} strokeWidth={1.5} aria-hidden="true" /></span><span className="step-number">0{index + 1}</span></div><h3>{step.title}</h3><p>{step.description}</p></article>)}</div></section>
    <section className="topics-section"><div className="container"><div className="section-intro"><div><p className="eyebrow">LO QUE IMPORTA</p><h2>La política está en lo cotidiano.</h2></div><Link className="text-link" to="/test">Explora tus ideas<ArrowRight size={17} aria-hidden="true" /></Link></div><p className="section-description">Desde el alquiler de tu casa hasta el futuro de la tecnología. {categories.length} temas, distintas perspectivas.</p><div className="topic-chips">{categories.map(category => <Link to="/test" key={category.id} className="topic-chip"><CategoryIcon name={category.icon} size={18} />{category.name}</Link>)}</div></div></section>
    <section className="neutrality-section container"><span className="neutrality-icon"><Compass size={28} strokeWidth={1.4} aria-hidden="true" /></span><div><p className="eyebrow">INFORMACIÓN PARA DECIDIR, LIBERTAD PARA ELEGIR</p><h2>Ningún algoritmo decide por ti.</h2><p>{config.name} no recomienda partidos ni candidatos. Su objetivo es facilitar la comparación de propuestas políticas utilizando información verificable.</p><Link className="text-link" to="/metodologia">Conoce nuestra metodología<ArrowUpRight size={17} aria-hidden="true" /></Link></div><div className="neutrality-stamp" aria-hidden="true"><OrbitMark /></div></section>
  </div>;
}
function BriefcaseIcon() { return <CategoryIcon name="BriefcaseBusiness" size={15} />; }
