import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, ShieldCheck, Trash2, Github } from 'lucide-react';
import { categories, questions, parties, sources, proposals, dataset, categoryName, sourceTypeLabels } from '../data';
import { useAppState } from '../hooks/useAppState';
import { PageHeading, MatchBadge, PartyMark, SourceLink } from '../components/ui';
import { GitHubLink } from '../layouts/Layout';
import { formatDate } from '../utils/format';
import config from '../config.json';
export function Methodology(){return <div className="container page information-page"><PageHeading eyebrow="CÓMO FUNCIONA, SIN CAJAS NEGRAS" title="La transparencia es el punto de partida." description={`Datos comprobados por última vez: ${formatDate(dataset.lastVerified)}. La comparación describe medidas independientes; no mide ideología ni recomienda un voto.`}/><div className="prose">
<section><h2>Ámbito y fecha</h2><p>{dataset.scope}</p><p>Las Cámaras fueron disueltas el 06/10/2026 por el Real Decreto 806/2026. Las elecciones están convocadas para el 29/11/2026. Los programas de este corpus pertenecen a las generales del 23/07/2023: son antecedentes documentales, sin presunción de vigencia para la nueva elección. No se reutilizan como cifras actuales los miembros de una Diputación Permanente.</p><p>No se llama candidato a un líder. Este conjunto no contiene candidaturas oficialmente publicadas para la convocatoria de 2026.</p></section>
<section><h2>Formaciones, coaliciones y grupos</h2><p>El índice del Senado identifica las formaciones incluidas, complementado por documentación del Congreso sobre Podemos y el Grupo Mixto, el programa de la coalición Sumar de 2023 y la aportación propia de IU. Es una primera selección documental, no un censo exhaustivo de afiliaciones de cada diputado.</p><p>Movimiento Sumar (partido), Sumar 2023 (coalición electoral), su candidatura de 2023 y el Grupo Plurinacional Sumar son registros diferentes. Las relaciones tienen fuente y ámbito temporal. Una coalición no transmite automáticamente todas sus propuestas a cada integrante. Los componentes sin documento propio comparable mantienen posiciones desconocidas.</p></section>
<section><h2>Fuentes y extracción</h2><p>Se priorizan programas y documentos oficiales del partido, seguidos de Congreso, Senado, BOE, JEC y otros organismos públicos. Una declaración oficial y una actuación parlamentaria conservan su tipo; no se presentan como programa. No se utilizan resúmenes de terceros, redes sociales o Wikipedia como evidencia primaria.</p><p>Los PDF se descargan y extraen por página. Cada registro conserva un fragmento literal, resumen neutral, documento, URL, fecha o fecha desconocida, elección, última comprobación y hash SHA-256. La página es el contador PDF, con la portada como 1; puede diferir de la paginación impresa. No se inventa una fecha de publicación a partir de la carpeta de subida.</p></section>
<section><h2>Medidas, asuntos y preguntas</h2><p>Los resúmenes conservan las condiciones y eliminan lenguaje persuasivo. Propuestas que describen una misma medida se vinculan a un asunto (issueId). Una medida puede pertenecer a varias categorías; el cuestionario contiene {questions.length} cuestiones en una taxonomía de {categories.length} temas.</p><p>Las preguntas se generan a partir de asuntos previamente revisados con evidencia comparable. Los controles verifican trazabilidad, duplicados, presencia de fuente, términos persuasivos y ausencia de siglas. No se publica una pregunta que falle. Una comprobación automática no demuestra neutralidad semántica: la revisión es asistida y aún no tiene un revisor humano externo independiente.</p><p>Durante el test no se muestran atribuciones, documentos identificativos ni colores de formación. El contexto enumera argumentos posibles a favor y en contra y matices. La revelación aparece al terminar.</p></section>
<section><h2>Certeza y desconocidos</h2><p>Alta significa medida explícita. Media significa que requiere una interpretación documentada. Baja se conserva pendiente y no alimenta comparaciones. Cada desconocido se guarda como position=null y muestra: “No se ha encontrado una posición suficientemente clara en las fuentes consultadas.” No implica que la formación carezca de una postura; indica un límite de este corpus.</p><p>Una medida próxima no se considera automáticamente equivalente. Por ejemplo, tributar al menos el 15 % efectivo no equivale a reducir el tipo general de sociedades al 15 %. Cuota cero por ingresos bajos no equivale a cuota cero universal durante el primer año. Universalizar educación infantil sin mencionar gratuidad tampoco acredita el enunciado completo.</p></section>
<section><h2>Coincidencias por cuestión</h2><p>Las respuestas ofrecen cinco opciones y saltar. Acuerdo y acuerdo total expresan el mismo sentido para la comparación; no se atribuye a un partido una intensidad inventada. Neutral / No estoy seguro, saltos y ausencia de posición documentada producen “Sin información suficiente”.</p><div className="method-matches"><div><MatchBadge match="coincidence"/><p>Mismo sentido sobre la medida documentada.</p></div><div><MatchBadge match="partial"/><p>Mismo sentido, con condición o ámbito explícitos diferentes.</p></div><div><MatchBadge match="difference"/><p>Sentidos opuestos ante el enunciado.</p></div><div><MatchBadge match="unknown"/><p>Sin base suficiente o respuesta neutral/omitida.</p></div></div><p>Al terminar se calcula un porcentaje por formación: 100 × (coincidencias + 0,5 × coincidencias parciales) / preguntas comparables, redondeado al entero más cercano. Cada pregunta tiene el mismo peso. No entran neutrales, saltos, conflictos, evidencia de baja certeza ni posiciones desconocidas. La intensidad de acuerdo no modifica el sentido de la respuesta. Una coincidencia parcial es una convención de cálculo, no una medida empírica de afinidad política. Cada resultado muestra su base de preguntas: la cobertura varía entre formaciones, por lo que los porcentajes no son directamente equivalentes ni describen el programa completo. Se presentan de mayor a menor porcentaje; los empates muestran primero la base más amplia y después el orden alfabético. Cuando no hay preguntas comparables no se muestra un 0 %, sino un resultado sin porcentaje. La prioridad temática solo ordena el desglose personal. No se recomienda un voto.</p></section>
<section><h2>Actividad posterior y contradicciones</h2><p>Se conservan el programa y todos los registros posteriores con sus fechas. Una devolución de un proyecto que reúne jornada, registro horario y desconexión no se interpreta como oposición a cada medida. Las actuaciones de un grupo se atribuyen a ese grupo y no se heredan por todos sus partidos.</p><p>Si dos fuentes comparables documentan sentidos distintos, se marca conflicto, se conserva toda la historia y se deja la comparación sin posición única. No se decide cuál es la posición verdadera. En este primer corpus no se fabrica una contradicción a partir de silencios o votos sobre paquetes de medidas.</p></section>
<section><h2>Cobertura y actualización</h2><p>{dataset.coverageNote} El mismo criterio de evidencia se aplica a todas las formaciones; las fuentes bloqueadas y programas no procesados se muestran en el estado de los datos. No se rellenan huecos por ideología ni por pertenencia a una coalición.</p><p>El comando update-data verifica enlaces y hashes y genera un informe pendiente. No sobrescribe medidas verificadas ni decide automáticamente que un documento nuevo mantiene las posiciones antiguas. La versión del corpus cambia tras la revisión; el progreso de un cuestionario anterior no se mezcla con preguntas nuevas.</p><p>El informe completo de datos y los textos extraídos están en la carpeta del proyecto. La aplicación funciona con archivos estáticos y no actualiza documentos ni envía respuestas a servidores durante el test.</p><Link className="text-link" to="/admin-data">Inspeccionar cobertura y pendientes<ArrowRight size={17} aria-hidden="true"/></Link></section>
<section id="codigo"><h2>Código y privacidad</h2><p>Tu mapa cuenta respuestas por tema sin etiquetas ideológicas. La imagen se genera en el navegador. Las respuestas permanecen en tu dispositivo. {config.githubUrl?'El repositorio público permite revisar el código.':'Esta copia local todavía no tiene un repositorio público asociado.'}</p><GitHubLink className="button secondary"/></section>
</div></div>;}
export function Sources(){
 const [query,setQuery]=useState('');const [theme,setTheme]=useState('all');const [type,setType]=useState('all');const [party,setParty]=useState('all');
 const displayed=sources.filter(s=>{
  const related=proposals.filter(p=>p.sourceId===s.id);const names=parties.filter(p=>s.partyIds.includes(p.id)).map(p=>`${p.name} ${p.acronym}`).join(' ');
  return `${s.sourceTitle} ${names}`.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es'))&&(type==='all'||type===s.sourceType)&&(party==='all'||s.partyIds.includes(party))&&(theme==='all'||related.some(p=>p.categories.includes(theme)));
 });
 return <div className="container page"><PageHeading eyebrow="CADA AFIRMACIÓN, A SU ORIGEN" title="Fuentes que puedes consultar." description={`Documentación primaria, tipos y fechas visibles. Datos comprobados por última vez: ${formatDate(dataset.lastVerified)}.`}/><div className="source-filters"><label className="search-input"><span className="sr-only">Buscar fuentes por documento o partido</span><input type="search" placeholder="Buscar documento o partido…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="select-label">Formación<select value={party} onChange={e=>setParty(e.target.value)}><option value="all">Todas las formaciones</option>{[...parties].sort((a,b)=>a.name.localeCompare(b.name,'es')).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label className="select-label">Tema<select value={theme} onChange={e=>setTheme(e.target.value)}><option value="all">Todos los temas</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="select-label">Tipo de fuente<select value={type} onChange={e=>setType(e.target.value)}><option value="all">Todos los tipos</option>{Object.entries(sourceTypeLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div><p role="status">{displayed.length} documentos encontrados</p><div className="sources-grid">{displayed.map(s=><article className="source-card" key={s.id}><div className="party-card-heading">{s.partyIds.length===1&&<PartyMark party={parties.find(p=>p.id===s.partyIds[0])!}/>}<div><h2>{s.sourceTitle}</h2><p>{s.partyIds.length?s.partyIds.map(id=>parties.find(p=>p.id===id)?.name).join(' · '):'Fuente institucional transversal'}</p></div></div><p className="eyebrow">{sourceTypeLabels[s.sourceType||'']}</p><SourceLink source={s}/><p className="muted">{s.verificationMethod}{s.verificationNote&&` · ${s.verificationNote}`}</p><p className="muted">{[...new Set(proposals.filter(p=>p.sourceId===s.id).flatMap(p=>p.categories))].map(categoryName).join(' · ')}</p></article>)}</div>{!displayed.length&&<p className="empty-message">No hay documentos procesados con estos filtros. No se presumen posiciones.</p>}<div className="prose"><p>Los accesos bloqueados o enlaces de descarga fallidos se conservan como incidencias y no como fuentes activas de posiciones. Consulta también la cobertura que falta.</p><Link className="text-link" to="/admin-data">Ver incidencias y cobertura<ArrowRight size={17} aria-hidden="true"/></Link></div></div>;
}
export function Privacy() {
  const { erase, progress } = useAppState();
  return <div className="container page information-page"><PageHeading eyebrow="TUS RESPUESTAS TE PERTENECEN" title="Privacidad, por diseño." description="Tus respuestas permanecen en este dispositivo y no se envían a ningún servidor." /><div className="privacy-hero"><ShieldCheck size={38} strokeWidth={1.5} aria-hidden="true" /><div><h2>Sin cuenta. Sin seguimiento. Sin envío de respuestas.</h2><p>No pedimos nombre, correo, teléfono, dirección ni ubicación. No usamos analítica, cookies de seguimiento ni identificadores publicitarios.</p></div></div><div className="prose"><section><h2>Qué se guarda en este navegador</h2><p>El almacenamiento local conserva tus respuestas, el paso del cuestionario y la importancia de los temas para que puedas continuar. También se guardan las preferencias de apariencia y tamaño de texto cuando las cambias. Los datos se asocian a este navegador y a esta dirección web, sin un identificador de usuario.</p><p>La aplicación no sincroniza datos entre dispositivos. Si usas navegación privada, borras datos del navegador o bloqueas el almacenamiento, el progreso puede no conservarse. Una persona con acceso a este mismo perfil del navegador puede acceder a los datos guardados.</p></section><section><h2>Qué ocurre al visitar la web</h2><p>El alojamiento recibe las solicitudes necesarias para servir la página y sus archivos. El proveedor de alojamiento puede procesar datos técnicos, como la dirección IP, conforme a sus condiciones. La aplicación no recoge esa información ni envía tus respuestas en las solicitudes.</p><p>Las tipografías, iconos y recursos de la aplicación se incluyen en la propia web. No se descargan de servicios externos. Al abrir una fuente externa, se aplican las condiciones de privacidad de ese sitio.</p></section><section><h2>Funcionamiento sin conexión</h2><p>Después de una primera carga completa de la versión de producción, la aplicación puede guardar sus archivos mediante un service worker. Así puedes continuar parcialmente sin conexión. Los enlaces a documentos externos requieren internet. Esta caché contiene archivos de la aplicación, no una copia adicional de tus respuestas.</p></section><section><h2>Compartir tu mapa</h2><p>La descarga de imagen ocurre íntegramente en el navegador. Incluye tu perfil temático, sin partidos ni recomendación de voto. Puedes revisar la imagen antes de compartirla. La aplicación no la publica ni la envía a otras personas.</p></section></div><section className="erase-panel"><div><h2>Borrar mis respuestas</h2><p>{Object.keys(progress.answers).length} respuestas guardadas. Este botón elimina inmediatamente las respuestas y preferencias de esta plataforma en el navegador.</p></div><button className="button danger" onClick={erase}><Trash2 size={18} aria-hidden="true" />Borrar mis respuestas</button></section></div>;
}
export function About() {
  return <div className="container page information-page"><PageHeading eyebrow="UN ESPACIO PARA PENSAR" title="Tus ideas. Tu criterio." description={`${config.name} nace para hacer las propuestas más fáciles de entender y comparar, sin tomar la decisión por ti.`} /><div className="prose"><section><h2>Una herramienta independiente</h2><p>La aplicación no está afiliada a ninguna formación. Al terminar el cuestionario muestra porcentajes de coincidencia sobre posiciones documentadas y la base disponible para cada partido. No ofrece recomendaciones de voto. Los porcentajes no representan la afinidad con todo el programa ni una probabilidad de voto.</p><p>Esta edición utiliza documentación primaria real. Los programas electorales son antecedentes de 2023 y la actividad parlamentaria conserva su fecha. El contexto describe argumentos posibles; no son efectos causales demostrados. La cobertura y la selección requieren revisión continuada.</p></section><section><h2>Datos y revisión editorial</h2><p>Cada medida debe vincularse a documentación primaria verificable. La selección de propuestas, su redacción y la codificación de posiciones necesitan una revisión editorial que reconozca incertidumbre y evite sesgos. La plataforma hace visible la cobertura, pero no sustituye ese trabajo.</p><Link className="text-link" to="/metodologia">Leer la metodología<ArrowRight size={17} aria-hidden="true" /></Link></section><section id="codigo"><h2><Github size={25} aria-hidden="true" /> Código y datos del proyecto</h2>{config.githubUrl ? <><p>El código y los datos de esta plataforma son públicos en el repositorio del proyecto. Puedes revisar la comparación, proponer correcciones y aportar documentación.</p><a className="button secondary" href={config.githubUrl} target="_blank" rel="noopener noreferrer">Ver código en GitHub<ArrowUpRight size={17} aria-hidden="true" /></a></> : <><p>Esta versión se ejecuta localmente. Todavía no se ha asociado un repositorio público. El código y los datos están disponibles en la carpeta del proyecto, con instrucciones de instalación, contribución y despliegue en su README.</p><p>Al publicar tu repositorio, añade su URL en <code>src/config.json</code>, en el campo <code>githubUrl</code>. Los enlaces de GitHub mostrarán entonces el repositorio real.</p><Link className="button secondary" to="/fuentes">Explorar los documentos incluidos<ArrowRight size={17} aria-hidden="true" /></Link></>}</section><section><h2>Accesibilidad y control</h2><p>Puedes navegar con teclado, aumentar el tamaño de texto y elegir apariencia clara, oscura o del sistema desde el pie de página. Las animaciones respetan la preferencia de reducción de movimiento. Los gráficos incluyen explicaciones y tablas accesibles.</p><p>Si decides instalar la web, el navegador mostrará la opción cuando la plataforma y la conexión segura lo permitan. También puedes añadirla a la pantalla de inicio desde el menú de tu navegador.</p></section></div></div>;
}
