import { Link, useParams, useSearchParams } from 'react-router-dom';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, ArrowLeft, Search, BookOpen, Calendar } from 'lucide-react';
import { alphabeticalParties, categories, proposals, entities, sourceTypeLabels, unknownPosition, sourceIncidents, categoryName } from '../data';
import { EmptyState, PageHeading, PartyMark, SourceLink } from '../components/ui';
import { formatDate } from '../utils/format';
const typeLabels={party:'Partido',coalition:'Coalición',federation:'Federación'};
export function Parties() {
 const [query,setQuery]=useState('');const filtered=alphabeticalParties.filter(p=>`${p.name} ${p.acronym}`.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es')));
 return <div className="container page"><PageHeading eyebrow="INFORMACIÓN, SIN INTERMEDIARIOS" title="Conoce las propuestas." description="Partidos, coaliciones y grupos son entidades diferentes. Las fichas enlazan documentos propios y conservan el ámbito de cada elección."/><div className="explorer-toolbar"><p>{alphabeticalParties.length} fichas · Orden alfabético</p><label className="search-input"><Search size={18} aria-hidden="true"/><span className="sr-only">Buscar partido</span><input type="search" placeholder="Buscar partido…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="party-grid">{filtered.map(p=><article className="party-card" key={p.id}><div className="party-card-top"><PartyMark party={p}/><span className="dataset-badge">{typeLabels[p.type]}</span></div><span className="party-acronym">{p.acronym}</span><h2>{p.name}</h2><p>{p.description}</p><div className="party-program-info"><BookOpen size={17} aria-hidden="true"/><span>{p.programs.length?`${p.programs.length} documento programático relacionado`:'Programa propio sin procesar'}<br/><small>{proposals.filter(x=>x.partyId===p.id).length} propuestas o actuaciones documentadas</small></span></div><Link className="button secondary full" to={`/partidos/${p.slug}`}>Ver documentación<ArrowRight size={18} aria-hidden="true"/></Link></article>)}</div>{!filtered.length&&<EmptyState title="No encontramos esa formación" text="Prueba con el nombre o las siglas." action="Consultar fuentes" to="/fuentes"/>}<div className="inline-callout"><BookOpen size={21} aria-hidden="true"/><p>La documentación es histórica y la cobertura incompleta. Las relaciones de coalición no atribuyen automáticamente posiciones a sus integrantes.</p><Link className="text-link" to="/admin-data">Examinar cobertura</Link></div></div>;
}
export function PartyDetail() {
 const {slug}=useParams();const [params]=useSearchParams();const party=alphabeticalParties.find(p=>p.slug===slug);const [theme,setTheme]=useState('all');
 if(!party)return <div className="container page"><EmptyState headingLevel={1} title="No se encuentra esta formación" text="La dirección no corresponde a una ficha disponible." to="/partidos" action="Ver partidos"/></div>;
 const documented=proposals.filter(p=>p.partyId===party.id);const filtered=documented.filter(p=>(theme==='all'||p.categories.includes(theme))&&(!params.get('issue')||p.issueId===params.get('issue')));const incidents=sourceIncidents.filter(i=>i.partyId===party.id);
 return <div className="container page party-detail"><Link className="text-link subtle back-link" to="/partidos"><ArrowLeft size={17} aria-hidden="true"/>Todas las formaciones</Link><header className="party-detail-header"><PartyMark party={party}/><div><span className="dataset-badge">{typeLabels[party.type]}</span><h1>{party.name}</h1><p>{party.description}</p></div></header><div className="program-metadata"><div><Calendar size={20} aria-hidden="true"/><span><strong>Datos comprobados por última vez</strong>{formatDate(party.lastVerified)}</span></div><div><BookOpen size={20} aria-hidden="true"/><span><strong>Documentos programáticos relacionados</strong>{party.programs.length}</span></div></div>{party.website&&<a className="text-link" href={party.website} target="_blank" rel="noopener noreferrer">Sitio oficial<ArrowUpRight size={16} aria-hidden="true"/><span className="sr-only"> (otra pestaña)</span></a>}
 <section className="prose"><h2>Relaciones documentadas</h2><ul>{party.relations.map((r,i)=><li key={i}>{entities.find(e=>e.id===r.entityId)?.name||alphabeticalParties.find(p=>p.id===r.entityId)?.name||r.entityId}. {r.validity} <a href={r.sourceUrl} target="_blank" rel="noopener noreferrer">Fuente de la relación</a></li>)}</ul><p>Movimiento Sumar, coalición Sumar de 2023 y grupo parlamentario Sumar se registran por separado. El documento de la coalición no se hereda por IU, Podemos, Compromís o Más Madrid.</p></section>
 {party.programs.length>0&&<section className="prose"><h2>Programas y documentos relacionados</h2><ul>{party.programs.map(p=><li key={p.sourceId}><a href={p.url} target="_blank" rel="noopener noreferrer">{p.title}</a> · {p.election} · {p.date?formatDate(p.date):'Día de publicación no acreditado'}</li>)}</ul><p>Estos documentos pertenecen a la convocatoria de 2023. No se presentan como programa de las elecciones de 2026.</p></section>}
 {incidents.length>0&&<details className="proposal-details"><summary>Incidencias y cobertura pendiente ({incidents.length})</summary>{incidents.map(i=><p key={i.id}>{i.reason} {i.resolution}</p>)}</details>}
 <div className="section-intro"><div><h2>Propuestas y actividad documentada</h2><p className="muted">{documented.length} registros. Se distinguen por tipo y fecha.</p></div><label className="select-label">Tema<select value={theme} onChange={e=>setTheme(e.target.value)}><option value="all">Todos los temas</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
 {!filtered.length?<p className="empty-message">{unknownPosition}</p>:<div className="documented-proposals">{filtered.map(p=><article className="documented-card" key={p.id} id={p.id}><p className="category-label">{p.categories.map(categoryName).join(' · ')}</p><p className="eyebrow">{sourceTypeLabels[p.sourceType||'']}</p><h3>{p.neutralSummary}</h3>{p.attributedEntityId&&<p>Atribución: {entities.find(e=>e.id===p.attributedEntityId)?.name}</p>}<p className="muted">Certeza {p.certainty==='high'?'alta':p.certainty==='medium'?'media':'baja'} · {p.comparisonEligible?'Medida comparable':'Contexto relacionado; no asigna una coincidencia'}</p>{p.comparisonNote&&<p>{p.comparisonNote}</p>}<blockquote>{p.originalText}</blockquote><SourceLink source={p}/><Link className="text-link" to={`/comparar?parties=${party.id}&issue=${p.issueId}`}>Ver asunto {p.issueId} y su pregunta</Link><p className="muted">Propuesta: {p.id}</p></article>)}</div>}
 </div>;
}
